version: '3.8'

services:
  mcp-server:
    build: .
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/api/v1/mpc", "-H", "Content-Type: application/json", "-d", '{"jsonrpc": "2.0", "id": 1, "method": "ping", "params": {}}']
      interval: 30s
      timeout: 10s
      retries: 3 