spring:
  application:
    name: mcp-server
  ai:
    mcp:
      server:
        name: webflux-mcp-server
        version: 1.0.0
        type: ASYNC  # Recommended for reactive applications
        sse-message-endpoint: /mcp/messages

server:
  port: 8090
  address: 0.0.0.0

logging:
  level:
    org.springframework.ai: DEBUG
    com.example.mcpserver: DEBUG 