name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Create Release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false
        body: |
          ## 🚀 What's New in ${{ github.ref }}
          
          ### Features
          - MCP Server implementation with Spring Boot
          - Calculator and Weather tools
          - RESTful API endpoints
          - Docker containerization
          - Comprehensive testing
          
          ### Technical Details
          - Java 17
          - Spring Boot 3.2.0
          - Maven build system
          - Docker support
          
          ### Quick Start
          ```bash
          # Run locally
          mvn spring-boot:run
          
          # Run with Docker
          docker run -p 8080:8080 ghcr.io/${{ github.repository }}:${{ github.ref }}
          ```
          
          ### API Documentation
          - Health Check: `GET /api/v1/health`
          - List Tools: `GET /api/v1/tools`
          - Execute Tool: `POST /api/v1/tools/call`
          
          ### Docker Image
          ```bash
          docker pull ghcr.io/${{ github.repository }}:${{ github.ref }}
          ```
    
    - name: Upload JAR to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/mcp-server-1.0.0.jar
        asset_name: mcp-server-${{ github.ref }}.jar
        asset_content_type: application/java-archive 